server {
    listen 80;
    server_name localhost;

    # Direktori tempat file web disimpan di dalam container
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Header tambahan (Berguna jika berada di belakang Load Balancer)
    location ~ /\.ht {
        deny all;
    }
}